# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  master:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: zip -r filename-1.zip dist/
        
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 65.2.124.196
        username: root
        port: 22
        key: ${{ secrets.Key }}
        source: "filename-1.zip"
        target: "/home/ubuntu/"
        
    - name: ls -a via ssh
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: |
             sudo apt-get install nginx -y
             sudo systemctl start nginx
             unzip -o /home/ubuntu/filename-1.zip
             sudo rm -rf /var/www/html/*
             sudo mv -f dist/* /var/www/html/ 
             
        host: 65.2.124.196
        user: root
        key: ${{ secrets.key}} 
        
  dev:

     runs-on: ubuntu-latest

     strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

     steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
     - run: npm install
     - run: npm run build --if-present
     - run: zip -r filename.zip dist/
        
     - name: copy file via ssh key
       uses: appleboy/scp-action@master
       with:
        host: 65.1.94.252
        username: ubuntu
        port: 22
        key: ${{ secrets.Key }}
        source: "filename.zip"
        target: "/home/ubuntu/"
        
     - name: ls -a via ssh
       uses: tarunjangra/ssh-remote-cmd@v1
       with:
        command: |
             sudo apt-get install nginx -y
             sudo systemctl start nginx
             sudo apt-get install unzip
             unzip -o /home/ubuntu/filename.zip
             sudo rm -rf /var/www/html/*
             sudo mv -f /home/ubuntu/dist/* /var/www/html/
             
        host: 65.1.94.252
        user: ubuntu
        key: ${{ secrets.key}} 
