# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - "master"
      - "prod"
    
jobs:
  master:
     
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     - run: npm install
     - run: npm run build --if-present
        
     - name: copy file via ssh key
       if: github.ref == 'refs/heads/master'
       uses: appleboy/scp-action@master
       with:
         host: 13.127.214.77
         username: root
         port: 22
         key: ${{ secrets.Key }}
         source: "frontend.zip"
         target: "/home/ubuntu/"
               
     - name: ls -a via ssh
       if: github.ref == 'refs/heads/master'   
       uses: tarunjangra/ssh-remote-cmd@v1
       with:
         command: |
             sudo apt-get install nginx -y
             sudo systemctl start nginx
             unzip -o /home/ubuntu/frontend.zip
             sudo rm -rf /var/www/html/*
             sudo mv -f dist/* /var/www/html/      
         host: 13.127.214.77
         user: root
         key: ${{ secrets.key}} 
         
         
     - name: ls -a via ssh
       if: github.ref == 'refs/heads/prod' 
       uses: tarunjangra/ssh-remote-cmd@v1
       with:
         host: 13.127.214.77
         username: root
         port: 22
         key: ${{ secrets.Key }}
         command: |
              sudo mkdir -p /home/ubuntu/backup
              sudo zip -r /home/ubuntu/backup/frontend.zip dist/  
                             
     - name: copy file via ssh key
       if: github.ref == 'refs/heads/prod'
       uses: appleboy/scp-action@master
       with:
         host: 13.127.214.77
         username: root
         port: 22
         key: ${{ secrets.Key }}
         source: "frontend.zip"
         target: "/home/ubuntu/"
        
     - name: ls -a via ssh
       if: github.ref == 'refs/heads/prod' 
       uses: tarunjangra/ssh-remote-cmd@v1
       with:
         command: |
             sudo apt-get install nginx -y
             sudo systemctl start nginx
             unzip -o /home/ubuntu/backup/frontend.zip
             sudo rm -rf /var/www/html/*
             sudo mv -f /home/ubuntu/dist/* /var/www/html/ 
         host: 13.127.214.77
         user: root
         key: ${{ secrets.key}} 
        
